### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by jbeck28** [ros-industrial/abb_egm_rws_managers#13]
I'm trying to make use of the RWSStateMachineInterface which is the RWSManager class. But I'm hung up on how to use the [runService method](https://github.com/ros-industrial/abb_egm_rws_managers/blob/ea7d418e7b34aaacc033365d5326b6a6befde3df/include/abb_egm_rws_managers/rws_manager.h#L115)

Can someone illuminate to me how to make calls to methods from RWSStateMachineInterface?

Thanks!

**Comment by jbeck28** [comment]
We figured this out... here's a snippet if anyone is as inept as I am:

```C++
rws_manager_->runPriorityService(
    [](abb::rws::RWSStateMachineInterface& interface) {
      // Your code that uses the interface goes here
      // For example:
      // interface.someMethodOfRWSStateMachineInterface();
    }
);
```

**Comment by gavanderhoorn** [comment]
For future reference: the function(s) you mention are used in `abb_robot_driver`. [Here](https://github.com/ros-industrial/abb_robot_driver/blob/ed45d5c761e52b8e6a0d5b734ee0ced9b2631610/abb_rws_service_provider/src/rws_service_provider_sm_srvs.cpp#L389) fi.

PS: as this isn't/wasn't an issue, could you please post questions like this on the Discussion forum? thanks.
